language: rust

sudo: required

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

stage: build and test

cache:
  cargo: true
  directories:
    - $HOME/.ccache

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

script: ./ci/travis_test.sh

after_success: ./ci/mk_coverage.sh

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    #- stage: pre-build checks
      #rust: stable
      #name: "Rustfmt coding style conformance"
      #addons: { }
      #cache: false
      #before_script: rustup component add rustfmt
      #script:
        #- cargo fmt -- --check
      #after_success:
    - stage: static analysis
      name: "Clippy"
      addons: { }
      rust: stable
      cache:
        cargo: true
      before_script: rustup component add clippy
      script: cargo clippy -- -D clippy::all
      after_success:

stages:
    - pre-build checks
    - build and test
    - lints
