language: rust

sudo: required

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - stage: rustfmt
      name: "Style check"
      rust: stable
      cache: false
      before_script: rustup component add rustfmt-preview
      script:
        - cargo fmt -- --write-mode=check
    - stage: test
      name: "Test suite (stable)"
      rust: stable
      cache:
        cargo: true
        apt: true
        ccache: true
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
      script: ./ci/travis_test.sh
      after_success: ./ci/mk_coverage.sh
    - name: "Test suite (beta)"
      rust: beta
      cache:
        cargo: true
        apt: true
        ccache: true
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
      script: ./ci/travis_test.sh
      after_success: ./ci/mk_coverage.sh
    - name: "Test suite (nightly)"
      rust: nightly
      cache:
        cargo: true
        apt: true
        ccache: true
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev
      script: ./ci/travis_test.sh
      after_success: ./ci/mk_coverage.sh

stages:
    - rustfmt
    - test
    #- clippy
