[package]
name = "ndimage"
version = "0.1.0"
authors = ["Robin Chavignat"]

[dependencies]
byteorder = "1.2.*"
failure = "0.1.*"
ndarray = "0.11.*"
num-traits = "0.2.*"
png = "0.11.*"

[dev-dependencies]
image = "0.18.0"
